spring.application.name=bank-account-management-system
server.port=9091
#database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/bank_account-management_system
spring.datasource.username=root
spring.datasource.password=Nil007ingole33
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=update
# Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
# Security Configuration
jwt.secret=U3VwZXJTZWNyZXRLZXlGb3JKV1QxMjM0NTY3OA==
jwt.expiration=3600000